cmc_quote = {
    "status": {
        "timestamp": "2025-02-18T01:19:34.107Z",
        "error_code": 0,
        "error_message": None,
        "elapsed": 27,
        "credit_count": 1,
        "notice": None,
    },
    "data": {
        "1": {
            "id": 1,
            "name": "Bitcoin",
            "symbol": "BTC",
            "slug": "bitcoin",
            "num_market_pairs": 11945,
            "date_added": "2010-07-13T00:00:00.000Z",
            "tags": [
                {"slug": "mineable", "name": "Mineable", "category": "OTHERS"},
                {"slug": "pow", "name": "PoW", "category": "ALGORITHM"},
                {"slug": "sha-256", "name": "SHA-256", "category": "ALGORITHM"},
                {
                    "slug": "store-of-value",
                    "name": "Store Of Value",
                    "category": "CATEGORY",
                },
                {
                    "slug": "state-channel",
                    "name": "State Channel",
                    "category": "CATEGORY",
                },
                {
                    "slug": "coinbase-ventures-portfolio",
                    "name": "Coinbase Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "three-arrows-capital-portfolio",
                    "name": "Three Arrows Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "polychain-capital-portfolio",
                    "name": "Polychain Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "binance-labs-portfolio",
                    "name": "Binance Labs Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "blockchain-capital-portfolio",
                    "name": "Blockchain Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "boostvc-portfolio",
                    "name": "BoostVC Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "cms-holdings-portfolio",
                    "name": "CMS Holdings Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "dcg-portfolio",
                    "name": "DCG Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "dragonfly-capital-portfolio",
                    "name": "DragonFly Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "electric-capital-portfolio",
                    "name": "Electric Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "fabric-ventures-portfolio",
                    "name": "Fabric Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "framework-ventures-portfolio",
                    "name": "Framework Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "galaxy-digital-portfolio",
                    "name": "Galaxy Digital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "huobi-capital-portfolio",
                    "name": "Huobi Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "alameda-research-portfolio",
                    "name": "Alameda Research Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "a16z-portfolio",
                    "name": "a16z Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "1confirmation-portfolio",
                    "name": "1Confirmation Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "winklevoss-capital-portfolio",
                    "name": "Winklevoss Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "usv-portfolio",
                    "name": "USV Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "placeholder-ventures-portfolio",
                    "name": "Placeholder Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "pantera-capital-portfolio",
                    "name": "Pantera Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "multicoin-capital-portfolio",
                    "name": "Multicoin Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "paradigm-portfolio",
                    "name": "Paradigm Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "bitcoin-ecosystem",
                    "name": "Bitcoin Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "ftx-bankruptcy-estate",
                    "name": "FTX Bankruptcy Estate ",
                    "category": "CATEGORY",
                },
                {
                    "slug": "2017-2018-alt-season",
                    "name": "2017/18 Alt season",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": 21000000,
            "circulating_supply": 19825784,
            "total_supply": 19825784,
            "is_active": 1,
            "infinite_supply": False,
            "platform": None,
            "cmc_rank": 1,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:18:00.000Z",
            "quote": {
                "USD": {
                    "price": 95998.6930944606,
                    "volume_24h": 27149855661.44612,
                    "volume_change_24h": 63.8264,
                    "percent_change_1h": 0.13789229,
                    "percent_change_24h": -0.39289516,
                    "percent_change_7d": -2.01924622,
                    "percent_change_30d": -7.67814266,
                    "percent_change_60d": -0.74511747,
                    "percent_change_90d": 4.29988356,
                    "market_cap": 1903249353573.0674,
                    "market_cap_dominance": 59.8152,
                    "fully_diluted_market_cap": 2015972554983.67,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:18:00.000Z",
                }
            },
        },
        "52": {
            "id": 52,
            "name": "XRP",
            "symbol": "XRP",
            "slug": "xrp",
            "num_market_pairs": 1534,
            "date_added": "2013-08-04T00:00:00.000Z",
            "tags": [
                {
                    "slug": "medium-of-exchange",
                    "name": "Medium of Exchange",
                    "category": "INDUSTRY",
                },
                {
                    "slug": "enterprise-solutions",
                    "name": "Enterprise Solutions",
                    "category": "INDUSTRY",
                },
                {
                    "slug": "xrp-ecosystem",
                    "name": "XRP Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "arrington-xrp-capital-portfolio",
                    "name": "Arrington XRP Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "galaxy-digital-portfolio",
                    "name": "Galaxy Digital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "a16z-portfolio",
                    "name": "a16z Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "pantera-capital-portfolio",
                    "name": "Pantera Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "ftx-bankruptcy-estate",
                    "name": "FTX Bankruptcy Estate ",
                    "category": "CATEGORY",
                },
                {
                    "slug": "2017-2018-alt-season",
                    "name": "2017/18 Alt season",
                    "category": "CATEGORY",
                },
                {
                    "slug": "klaytn-ecosystem",
                    "name": "Klaytn Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "made-in-america",
                    "name": "Made in America",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": 100000000000,
            "circulating_supply": 57818864895,
            "total_supply": 99986451428,
            "is_active": 1,
            "infinite_supply": False,
            "platform": None,
            "cmc_rank": 3,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:19:00.000Z",
            "quote": {
                "USD": {
                    "price": 2.647923284215714,
                    "volume_24h": 4755192945.526625,
                    "volume_change_24h": 38.196,
                    "percent_change_1h": -0.20917939,
                    "percent_change_24h": -3.87450028,
                    "percent_change_7d": 8.26356721,
                    "percent_change_30d": -18.61651366,
                    "percent_change_60d": 16.03845162,
                    "percent_change_90d": 139.52697309,
                    "market_cap": 153099918622.39307,
                    "market_cap_dominance": 4.8116,
                    "fully_diluted_market_cap": 264792328421.57,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:19:00.000Z",
                }
            },
        },
        "74": {
            "id": 74,
            "name": "Dogecoin",
            "symbol": "DOGE",
            "slug": "dogecoin",
            "num_market_pairs": 1163,
            "date_added": "2013-12-15T00:00:00.000Z",
            "tags": [
                {"slug": "mineable", "name": "Mineable", "category": "OTHERS"},
                {"slug": "pow", "name": "PoW", "category": "ALGORITHM"},
                {"slug": "scrypt", "name": "Scrypt", "category": "ALGORITHM"},
                {
                    "slug": "medium-of-exchange",
                    "name": "Medium of Exchange",
                    "category": "INDUSTRY",
                },
                {"slug": "memes", "name": "Memes", "category": "INDUSTRY"},
                {"slug": "payments", "name": "Payments", "category": "INDUSTRY"},
                {
                    "slug": "doggone-doggerel",
                    "name": "Doggone Doggerel",
                    "category": "CATEGORY",
                },
                {
                    "slug": "ftx-bankruptcy-estate",
                    "name": "FTX Bankruptcy Estate ",
                    "category": "CATEGORY",
                },
                {
                    "slug": "made-in-america",
                    "name": "Made in America",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": None,
            "circulating_supply": 148090216383.7052,
            "total_supply": 148090216383.7052,
            "is_active": 1,
            "infinite_supply": True,
            "platform": None,
            "cmc_rank": 8,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:19:00.000Z",
            "quote": {
                "USD": {
                    "price": 0.25788204793830843,
                    "volume_24h": 1373401222.3859115,
                    "volume_change_24h": 42.239,
                    "percent_change_1h": -0.05913185,
                    "percent_change_24h": -3.46770104,
                    "percent_change_7d": 0.17526652,
                    "percent_change_30d": -35.70143385,
                    "percent_change_60d": -17.21411584,
                    "percent_change_90d": -33.32242601,
                    "market_cap": 38189808280.657135,
                    "market_cap_dominance": 1.2005,
                    "fully_diluted_market_cap": 38189808280.66,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:19:00.000Z",
                }
            },
        },
        "512": {
            "id": 512,
            "name": "Stellar",
            "symbol": "XLM",
            "slug": "stellar",
            "num_market_pairs": 676,
            "date_added": "2014-08-05T00:00:00.000Z",
            "tags": [
                {
                    "slug": "medium-of-exchange",
                    "name": "Medium of Exchange",
                    "category": "INDUSTRY",
                },
                {
                    "slug": "enterprise-solutions",
                    "name": "Enterprise Solutions",
                    "category": "INDUSTRY",
                },
                {
                    "slug": "decentralized-exchange-dex-token",
                    "name": "Decentralized Exchange (DEX) Token",
                    "category": "CATEGORY",
                },
                {
                    "slug": "smart-contracts",
                    "name": "Smart Contracts",
                    "category": "CATEGORY",
                },
                {
                    "slug": "hashkey-capital-portfolio",
                    "name": "Hashkey Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "2017-2018-alt-season",
                    "name": "2017/18 Alt season",
                    "category": "CATEGORY",
                },
                {
                    "slug": "made-in-america",
                    "name": "Made in America",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": 50001806812,
            "circulating_supply": 30613000718.939167,
            "total_supply": 50001786894.450165,
            "is_active": 1,
            "infinite_supply": False,
            "platform": None,
            "cmc_rank": 13,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:19:00.000Z",
            "quote": {
                "USD": {
                    "price": 0.3331789710875155,
                    "volume_24h": 223078426.63216487,
                    "volume_change_24h": 33.5327,
                    "percent_change_1h": -0.11203328,
                    "percent_change_24h": -3.8258019,
                    "percent_change_7d": 4.94553549,
                    "percent_change_30d": -31.4601816,
                    "percent_change_60d": -10.36801459,
                    "percent_change_90d": 41.3170557,
                    "market_cap": 10199608081.437523,
                    "market_cap_dominance": 0.3206,
                    "fully_diluted_market_cap": 16659550546.14,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:19:00.000Z",
                }
            },
        },
        "825": {
            "id": 825,
            "name": "Tether USDt",
            "symbol": "USDT",
            "slug": "tether",
            "num_market_pairs": 116967,
            "date_added": "2015-02-25T00:00:00.000Z",
            "tags": [
                {"slug": "stablecoin", "name": "Stablecoin", "category": "CATEGORY"},
                {
                    "slug": "asset-backed-stablecoin",
                    "name": "Asset-Backed Stablecoin",
                    "category": "CATEGORY",
                },
                {
                    "slug": "ethereum-ecosystem",
                    "name": "Ethereum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "waves-ecosystem",
                    "name": "Waves Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "bitcoin-cash-ecosystem",
                    "name": "Bitcoin Cash Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "heco-ecosystem",
                    "name": "HECO Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "algorand-ecosystem",
                    "name": "Algorand Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "avalanche-ecosystem",
                    "name": "Avalanche Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "solana-ecosystem",
                    "name": "Solana Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "polygon-ecosystem",
                    "name": "Polygon Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "fantom-ecosystem",
                    "name": "Fantom Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "terra-ecosystem",
                    "name": "Terra Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "tezos-ecosystem",
                    "name": "Tezos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "near-protocol-ecosystem",
                    "name": "Near Protocol Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "arbitrum-ecosystem",
                    "name": "Arbitrum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "celo-ecosystem",
                    "name": "Celo Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "iotex-ecosystem",
                    "name": "IoTeX Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "zilliqa-ecosystem",
                    "name": "Zilliqa Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "harmony-ecosystem",
                    "name": "Harmony Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "moonriver-ecosystem",
                    "name": "Moonriver Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "cronos-ecosystem",
                    "name": "Cronos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "injective-ecosystem",
                    "name": "Injective Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "oasis-ecosystem",
                    "name": "Oasis Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "moonbeam-ecosystem",
                    "name": "Moonbeam Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "usd-stablecoin",
                    "name": "USD Stablecoin",
                    "category": "CATEGORY",
                },
                {
                    "slug": "xdc-ecosystem",
                    "name": "XDC Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "everscale-ecosystem",
                    "name": "Everscale Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "velas-ecosystem",
                    "name": "Velas Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "doge-chain-ecosystem",
                    "name": "Doge Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "ethereum-pow-ecosystem",
                    "name": "Ethereum PoW Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "aptos-ecosystem",
                    "name": "Aptos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "sui-ecosystem",
                    "name": "Sui Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "optimism-ecosystem",
                    "name": "Optimism Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "canto-ecosystem",
                    "name": "Canto Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "osmosis-ecosystem",
                    "name": "Osmosis Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "zksync-era-ecosystem",
                    "name": "zkSync Era Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "pulsechain-ecosystem",
                    "name": "Pulsechain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "sei-ecosystem",
                    "name": "Sei Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "toncoin-ecosystem",
                    "name": "Toncoin Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "fiat-stablecoin",
                    "name": "Fiat Stablecoin",
                    "category": "CATEGORY",
                },
                {
                    "slug": "viction-ecosystem",
                    "name": "Viction Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "gnosis-chain-ecosystem",
                    "name": "Gnosis Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "klaytn-ecosystem",
                    "name": "Klaytn Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "okexchain-ecosystem",
                    "name": "OKExChain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "conflux-ecosystem",
                    "name": "Conflux Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "kcc-ecosystem",
                    "name": "KCC Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "tron20-ecosystem",
                    "name": "Tron20 Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "kardiachain-ecosystem",
                    "name": "KardiaChain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "rsk-rbtc-ecosystem",
                    "name": "RSK RBTC Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "telos-ecosystem",
                    "name": "Telos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "boba-network-ecosystem",
                    "name": "Boba Network Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "fusion-network-ecosystem",
                    "name": "Fusion Network Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "hoo-smart-chain-ecosystem",
                    "name": "Hoo Smart Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "secret-ecosystem",
                    "name": "Secret Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "aurora-ecosystem",
                    "name": "Aurora Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "metis-andromeda-ecosystem",
                    "name": "Metis Andromeda Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "meter-ecosystem",
                    "name": "Meter Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "fuse-ecosystem",
                    "name": "Fuse Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "syscoin-ecosystem",
                    "name": "Syscoin Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "milkomeda-ecosystem",
                    "name": "Milkomeda Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "bitgert-ecosystem",
                    "name": "Bitgert Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "astar-ecosystem",
                    "name": "Astar Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "cube-network-ecosystem",
                    "name": "Cube network Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "thundercore-ecosystem",
                    "name": "ThunderCore Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "redlight-chain-ecosystem",
                    "name": "Redlight Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "core-ecosystem",
                    "name": "Core Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "polygon-zkevm-ecosystem",
                    "name": "Polygon zkEVM Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "eos-evm-ecosystem",
                    "name": "EOS EVM Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "starknet-ecosystem",
                    "name": "Starknet Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "mantle-ecosystem",
                    "name": "Mantle Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "neon-evm-ecosystem",
                    "name": "Neon EVM Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "manta-pacific-ecosystem",
                    "name": "Manta Pacific Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "scroll-ecosystem",
                    "name": "Scroll Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "x-layer-ecosystem",
                    "name": "X Layer Ecosystem",
                    "category": "PLATFORM",
                },
            ],
            "max_supply": None,
            "circulating_supply": 141762384601.69476,
            "total_supply": 143566824799.2221,
            "platform": {
                "id": 1027,
                "name": "Ethereum",
                "symbol": "ETH",
                "slug": "ethereum",
                "token_address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
            },
            "is_active": 1,
            "infinite_supply": True,
            "cmc_rank": 4,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:18:00.000Z",
            "quote": {
                "USD": {
                    "price": 0.9998731713718286,
                    "volume_24h": 73723546355.1827,
                    "volume_change_24h": 57.7383,
                    "percent_change_1h": -0.00589103,
                    "percent_change_24h": -0.0140026,
                    "percent_change_7d": -0.03240216,
                    "percent_change_30d": 0.08067415,
                    "percent_change_60d": 0.05800231,
                    "percent_change_90d": -0.13370592,
                    "market_cap": 141744405072.9294,
                    "market_cap_dominance": 4.4559,
                    "fully_diluted_market_cap": 143548616415.78,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:18:00.000Z",
                }
            },
        },
        "1027": {
            "id": 1027,
            "name": "Ethereum",
            "symbol": "ETH",
            "slug": "ethereum",
            "num_market_pairs": 9933,
            "date_added": "2015-08-07T00:00:00.000Z",
            "tags": [
                {"slug": "pos", "name": "PoS", "category": "ALGORITHM"},
                {
                    "slug": "smart-contracts",
                    "name": "Smart Contracts",
                    "category": "CATEGORY",
                },
                {
                    "slug": "ethereum-ecosystem",
                    "name": "Ethereum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "coinbase-ventures-portfolio",
                    "name": "Coinbase Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "three-arrows-capital-portfolio",
                    "name": "Three Arrows Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "polychain-capital-portfolio",
                    "name": "Polychain Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "heco-ecosystem",
                    "name": "HECO Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "binance-labs-portfolio",
                    "name": "Binance Labs Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "avalanche-ecosystem",
                    "name": "Avalanche Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "solana-ecosystem",
                    "name": "Solana Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "blockchain-capital-portfolio",
                    "name": "Blockchain Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "boostvc-portfolio",
                    "name": "BoostVC Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "cms-holdings-portfolio",
                    "name": "CMS Holdings Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "dcg-portfolio",
                    "name": "DCG Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "dragonfly-capital-portfolio",
                    "name": "DragonFly Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "electric-capital-portfolio",
                    "name": "Electric Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "fabric-ventures-portfolio",
                    "name": "Fabric Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "framework-ventures-portfolio",
                    "name": "Framework Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "hashkey-capital-portfolio",
                    "name": "Hashkey Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "kenetic-capital-portfolio",
                    "name": "Kenetic Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "huobi-capital-portfolio",
                    "name": "Huobi Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "alameda-research-portfolio",
                    "name": "Alameda Research Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "a16z-portfolio",
                    "name": "a16z Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "1confirmation-portfolio",
                    "name": "1Confirmation Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "winklevoss-capital-portfolio",
                    "name": "Winklevoss Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "usv-portfolio",
                    "name": "USV Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "placeholder-ventures-portfolio",
                    "name": "Placeholder Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "pantera-capital-portfolio",
                    "name": "Pantera Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "multicoin-capital-portfolio",
                    "name": "Multicoin Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "paradigm-portfolio",
                    "name": "Paradigm Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "tezos-ecosystem",
                    "name": "Tezos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "near-protocol-ecosystem",
                    "name": "Near Protocol Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "velas-ecosystem",
                    "name": "Velas Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "ethereum-pow-ecosystem",
                    "name": "Ethereum PoW Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "osmosis-ecosystem",
                    "name": "Osmosis Ecosystem",
                    "category": "PLATFORM",
                },
                {"slug": "layer-1", "name": "Layer 1", "category": "CATEGORY"},
                {
                    "slug": "ftx-bankruptcy-estate",
                    "name": "FTX Bankruptcy Estate ",
                    "category": "CATEGORY",
                },
                {
                    "slug": "zksync-era-ecosystem",
                    "name": "zkSync Era Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "viction-ecosystem",
                    "name": "Viction Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "klaytn-ecosystem",
                    "name": "Klaytn Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "sora-ecosystem",
                    "name": "Sora Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "rsk-rbtc-ecosystem",
                    "name": "RSK RBTC Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "starknet-ecosystem",
                    "name": "Starknet Ecosystem",
                    "category": "PLATFORM",
                },
            ],
            "max_supply": None,
            "circulating_supply": 120556761.34774569,
            "total_supply": 120556761.34774569,
            "is_active": 1,
            "infinite_supply": True,
            "platform": None,
            "cmc_rank": 2,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:18:00.000Z",
            "quote": {
                "USD": {
                    "price": 2731.3495345870556,
                    "volume_24h": 23380645593.17714,
                    "volume_change_24h": 132.8593,
                    "percent_change_1h": -0.28444087,
                    "percent_change_24h": 2.16203495,
                    "percent_change_7d": 1.33466739,
                    "percent_change_30d": -18.42735232,
                    "percent_change_60d": -19.7297302,
                    "percent_change_90d": -12.24575634,
                    "market_cap": 329282653998.4879,
                    "market_cap_dominance": 10.3487,
                    "fully_diluted_market_cap": 329282653998.49,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:18:00.000Z",
                }
            },
        },
        "1839": {
            "id": 1839,
            "name": "BNB",
            "symbol": "BNB",
            "slug": "bnb",
            "num_market_pairs": 2365,
            "date_added": "2017-07-25T00:00:00.000Z",
            "tags": [
                {"slug": "marketplace", "name": "Marketplace", "category": "INDUSTRY"},
                {
                    "slug": "centralized-exchange",
                    "name": "Centralized Exchange (CEX) Token",
                    "category": "CATEGORY",
                },
                {"slug": "payments", "name": "Payments", "category": "INDUSTRY"},
                {
                    "slug": "smart-contracts",
                    "name": "Smart Contracts",
                    "category": "CATEGORY",
                },
                {
                    "slug": "ethereum-ecosystem",
                    "name": "Ethereum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "alameda-research-portfolio",
                    "name": "Alameda Research Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "multicoin-capital-portfolio",
                    "name": "Multicoin Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "bnb-chain-ecosystem",
                    "name": "BNB Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {"slug": "layer-1", "name": "Layer 1", "category": "CATEGORY"},
                {
                    "slug": "alleged-sec-securities",
                    "name": "Alleged SEC Securities",
                    "category": "CATEGORY",
                },
                {
                    "slug": "celsius-bankruptcy-estate",
                    "name": "Celsius Bankruptcy Estate",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": None,
            "circulating_supply": 142477329.1,
            "total_supply": 142477329.1,
            "is_active": 1,
            "infinite_supply": False,
            "platform": None,
            "cmc_rank": 5,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:19:00.000Z",
            "quote": {
                "USD": {
                    "price": 665.3751351560397,
                    "volume_24h": 1930215153.209036,
                    "volume_change_24h": -4.6238,
                    "percent_change_1h": -0.09169117,
                    "percent_change_24h": -1.38350813,
                    "percent_change_7d": 7.34414827,
                    "percent_change_30d": -6.61361748,
                    "percent_change_60d": 0.16807771,
                    "percent_change_90d": 8.15735565,
                    "market_cap": 94800872106.58405,
                    "market_cap_dominance": 2.9802,
                    "fully_diluted_market_cap": 94800872106.58,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:19:00.000Z",
                }
            },
        },
        "1958": {
            "id": 1958,
            "name": "TRON",
            "symbol": "TRX",
            "slug": "tron",
            "num_market_pairs": 1119,
            "date_added": "2017-09-13T00:00:00.000Z",
            "tags": [
                {"slug": "media", "name": "Media", "category": "INDUSTRY"},
                {"slug": "payments", "name": "Payments", "category": "INDUSTRY"},
                {
                    "slug": "ethereum-ecosystem",
                    "name": "Ethereum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "tron-ecosystem",
                    "name": "TRON Ecosystem",
                    "category": "PLATFORM",
                },
                {"slug": "layer-1", "name": "Layer 1", "category": "CATEGORY"},
                {
                    "slug": "dwf-labs-portfolio",
                    "name": "DWF Labs Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "alleged-sec-securities",
                    "name": "Alleged SEC Securities",
                    "category": "CATEGORY",
                },
                {
                    "slug": "2017-2018-alt-season",
                    "name": "2017/18 Alt season",
                    "category": "CATEGORY",
                },
                {
                    "slug": "tron20-ecosystem",
                    "name": "Tron20 Ecosystem",
                    "category": "PLATFORM",
                },
            ],
            "max_supply": None,
            "circulating_supply": 86093342561.70056,
            "total_supply": 86093327507.8422,
            "is_active": 1,
            "infinite_supply": True,
            "platform": None,
            "cmc_rank": 10,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:19:00.000Z",
            "quote": {
                "USD": {
                    "price": 0.2386652478902472,
                    "volume_24h": 675328086.2353252,
                    "volume_change_24h": 52.7734,
                    "percent_change_1h": 0.14962177,
                    "percent_change_24h": -0.90644966,
                    "percent_change_7d": -3.56950192,
                    "percent_change_30d": -2.08545501,
                    "percent_change_60d": -5.03627713,
                    "percent_change_90d": 20.18399838,
                    "market_cap": 20547488944.188236,
                    "market_cap_dominance": 0.6458,
                    "fully_diluted_market_cap": 20547485351.36,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:19:00.000Z",
                }
            },
        },
        "2010": {
            "id": 2010,
            "name": "Cardano",
            "symbol": "ADA",
            "slug": "cardano",
            "num_market_pairs": 1461,
            "date_added": "2017-10-01T00:00:00.000Z",
            "tags": [
                {"slug": "dpos", "name": "DPoS", "category": "ALGORITHM"},
                {"slug": "pos", "name": "PoS", "category": "ALGORITHM"},
                {"slug": "platform", "name": "Platform", "category": "CATEGORY"},
                {"slug": "research", "name": "Research", "category": "INDUSTRY"},
                {
                    "slug": "smart-contracts",
                    "name": "Smart Contracts",
                    "category": "CATEGORY",
                },
                {"slug": "staking", "name": "Staking", "category": "CATEGORY"},
                {
                    "slug": "cardano-ecosystem",
                    "name": "Cardano Ecosystem",
                    "category": "PLATFORM",
                },
                {"slug": "cardano", "name": "Cardano", "category": "PLATFORM"},
                {"slug": "layer-1", "name": "Layer 1", "category": "CATEGORY"},
                {
                    "slug": "alleged-sec-securities",
                    "name": "Alleged SEC Securities",
                    "category": "CATEGORY",
                },
                {
                    "slug": "2017-2018-alt-season",
                    "name": "2017/18 Alt season",
                    "category": "CATEGORY",
                },
                {
                    "slug": "made-in-america",
                    "name": "Made in America",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": 45000000000,
            "circulating_supply": 35201193525.86875,
            "total_supply": 44994975100.72033,
            "is_active": 1,
            "infinite_supply": False,
            "platform": None,
            "cmc_rank": 9,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:18:00.000Z",
            "quote": {
                "USD": {
                    "price": 0.7943588674282742,
                    "volume_24h": 1037725385.141898,
                    "volume_change_24h": 119.5809,
                    "percent_change_1h": -1.51153698,
                    "percent_change_24h": 1.51880206,
                    "percent_change_7d": 7.07556749,
                    "percent_change_30d": -30.23146894,
                    "percent_change_60d": -10.07974484,
                    "percent_change_90d": 2.52787553,
                    "market_cap": 27962380221.3326,
                    "market_cap_dominance": 0.8788,
                    "fully_diluted_market_cap": 35746149034.27,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:18:00.000Z",
                }
            },
        },
        "3408": {
            "id": 3408,
            "name": "USDC",
            "symbol": "USDC",
            "slug": "usd-coin",
            "num_market_pairs": 25734,
            "date_added": "2018-10-08T00:00:00.000Z",
            "tags": [
                {
                    "slug": "medium-of-exchange",
                    "name": "Medium of Exchange",
                    "category": "INDUSTRY",
                },
                {"slug": "stablecoin", "name": "Stablecoin", "category": "CATEGORY"},
                {
                    "slug": "asset-backed-stablecoin",
                    "name": "Asset-Backed Stablecoin",
                    "category": "CATEGORY",
                },
                {
                    "slug": "ethereum-ecosystem",
                    "name": "Ethereum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "waves-ecosystem",
                    "name": "Waves Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "bitcoin-cash-ecosystem",
                    "name": "Bitcoin Cash Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "wanchain-ecosystem",
                    "name": "Wanchain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "coinbase-ventures-portfolio",
                    "name": "Coinbase Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "algorand-ecosystem",
                    "name": "Algorand Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "avalanche-ecosystem",
                    "name": "Avalanche Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "solana-ecosystem",
                    "name": "Solana Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "hedera-hashgraph-ecosystem",
                    "name": "Hedera Hashgraph Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "polygon-ecosystem",
                    "name": "Polygon Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "terra-ecosystem",
                    "name": "Terra Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "near-protocol-ecosystem",
                    "name": "Near Protocol Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "arbitrum-ecosystem",
                    "name": "Arbitrum Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "celo-ecosystem",
                    "name": "Celo Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "iotex-ecosystem",
                    "name": "IoTeX Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "harmony-ecosystem",
                    "name": "Harmony Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "moonriver-ecosystem",
                    "name": "Moonriver Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "cronos-ecosystem",
                    "name": "Cronos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "injective-ecosystem",
                    "name": "Injective Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "oasis-ecosystem",
                    "name": "Oasis Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "moonbeam-ecosystem",
                    "name": "Moonbeam Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "usd-stablecoin",
                    "name": "USD Stablecoin",
                    "category": "CATEGORY",
                },
                {
                    "slug": "everscale-ecosystem",
                    "name": "Everscale Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "velas-ecosystem",
                    "name": "Velas Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "doge-chain-ecosystem",
                    "name": "Doge Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "ethereum-pow-ecosystem",
                    "name": "Ethereum PoW Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "aptos-ecosystem",
                    "name": "Aptos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "sui-ecosystem",
                    "name": "Sui Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "optimism-ecosystem",
                    "name": "Optimism Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "canto-ecosystem",
                    "name": "Canto Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "osmosis-ecosystem",
                    "name": "Osmosis Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "zksync-era-ecosystem",
                    "name": "zkSync Era Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "pulsechain-ecosystem",
                    "name": "Pulsechain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "base-ecosystem",
                    "name": "Base Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "sei-ecosystem",
                    "name": "Sei Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "multiversx-ecosystem",
                    "name": "MultiversX Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "fiat-stablecoin",
                    "name": "Fiat Stablecoin",
                    "category": "CATEGORY",
                },
                {
                    "slug": "viction-ecosystem",
                    "name": "Viction Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "gnosis-chain-ecosystem",
                    "name": "Gnosis Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "okexchain-ecosystem",
                    "name": "OKExChain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "conflux-ecosystem",
                    "name": "Conflux Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "kcc-ecosystem",
                    "name": "KCC Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "tron20-ecosystem",
                    "name": "Tron20 Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "kardiachain-ecosystem",
                    "name": "KardiaChain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "telos-ecosystem",
                    "name": "Telos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "ronin-ecosystem",
                    "name": "Ronin Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "boba-network-ecosystem",
                    "name": "Boba Network Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "kava-ecosystem",
                    "name": "Kava Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "secret-ecosystem",
                    "name": "Secret Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "aurora-ecosystem",
                    "name": "Aurora Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "metis-andromeda-ecosystem",
                    "name": "Metis Andromeda Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "meter-ecosystem",
                    "name": "Meter Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "fuse-ecosystem",
                    "name": "Fuse Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "elastos-ecosystem",
                    "name": "Elastos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "syscoin-ecosystem",
                    "name": "Syscoin Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "milkomeda-ecosystem",
                    "name": "Milkomeda Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "evmos-ecosystem",
                    "name": "Evmos Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "bitgert-ecosystem",
                    "name": "Bitgert Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "astar-ecosystem",
                    "name": "Astar Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "thundercore-ecosystem",
                    "name": "ThunderCore Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "tomb-chain-ecosystem",
                    "name": "Tomb Chain Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "wemix-ecosystem",
                    "name": "Wemix Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "sx-network-ecosystem",
                    "name": "SX Network Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "godwoken-ecosystem",
                    "name": "Godwoken Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "energi-ecosystem",
                    "name": "Energi Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "core-ecosystem",
                    "name": "Core Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "polygon-zkevm-ecosystem",
                    "name": "Polygon zkEVM Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "starknet-ecosystem",
                    "name": "Starknet Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "mantle-ecosystem",
                    "name": "Mantle Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "neon-evm-ecosystem",
                    "name": "Neon EVM Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "scroll-ecosystem",
                    "name": "Scroll Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "shido-network-ecosystem",
                    "name": "Shido Network Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "made-in-america",
                    "name": "Made in America",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": None,
            "circulating_supply": 56468613877.49146,
            "total_supply": 56468613877.49146,
            "platform": {
                "id": 1027,
                "name": "Ethereum",
                "symbol": "ETH",
                "slug": "ethereum",
                "token_address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
            },
            "is_active": 1,
            "infinite_supply": False,
            "cmc_rank": 7,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:18:00.000Z",
            "quote": {
                "USD": {
                    "price": 0.9998780834450173,
                    "volume_24h": 6870682775.084362,
                    "volume_change_24h": 59.1231,
                    "percent_change_1h": -0.0004099,
                    "percent_change_24h": -0.00519996,
                    "percent_change_7d": -0.01658727,
                    "percent_change_30d": -0.01405008,
                    "percent_change_60d": -0.02511008,
                    "percent_change_90d": -0.01345029,
                    "market_cap": 56461729418.62287,
                    "market_cap_dominance": 1.775,
                    "fully_diluted_market_cap": 56461729418.62,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:18:00.000Z",
                }
            },
        },
        "5426": {
            "id": 5426,
            "name": "Solana",
            "symbol": "SOL",
            "slug": "solana",
            "num_market_pairs": 840,
            "date_added": "2020-04-10T00:00:00.000Z",
            "tags": [
                {"slug": "pos", "name": "PoS", "category": "ALGORITHM"},
                {"slug": "platform", "name": "Platform", "category": "CATEGORY"},
                {
                    "slug": "solana-ecosystem",
                    "name": "Solana Ecosystem",
                    "category": "PLATFORM",
                },
                {
                    "slug": "cms-holdings-portfolio",
                    "name": "CMS Holdings Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "kenetic-capital-portfolio",
                    "name": "Kenetic Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "alameda-research-portfolio",
                    "name": "Alameda Research Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "multicoin-capital-portfolio",
                    "name": "Multicoin Capital Portfolio",
                    "category": "CATEGORY",
                },
                {
                    "slug": "okx-ventures-portfolio",
                    "name": "OKX Ventures Portfolio",
                    "category": "CATEGORY",
                },
                {"slug": "layer-1", "name": "Layer 1", "category": "CATEGORY"},
                {
                    "slug": "ftx-bankruptcy-estate",
                    "name": "FTX Bankruptcy Estate ",
                    "category": "CATEGORY",
                },
                {
                    "slug": "alleged-sec-securities",
                    "name": "Alleged SEC Securities",
                    "category": "CATEGORY",
                },
                {
                    "slug": "cmc-crypto-awards-2024",
                    "name": "CMC Crypto Awards 2024",
                    "category": "CATEGORY",
                },
                {
                    "slug": "made-in-america",
                    "name": "Made in America",
                    "category": "CATEGORY",
                },
            ],
            "max_supply": None,
            "circulating_supply": 488389432.8278623,
            "total_supply": 594227387.0132306,
            "is_active": 1,
            "infinite_supply": True,
            "platform": None,
            "cmc_rank": 6,
            "is_fiat": 0,
            "self_reported_circulating_supply": None,
            "self_reported_market_cap": None,
            "tvl_ratio": None,
            "last_updated": "2025-02-18T01:18:00.000Z",
            "quote": {
                "USD": {
                    "price": 177.84723441251128,
                    "volume_24h": 4459257599.979638,
                    "volume_change_24h": 107.508,
                    "percent_change_1h": 0.41773931,
                    "percent_change_24h": -6.02830115,
                    "percent_change_7d": -11.95107618,
                    "percent_change_30d": -30.42852724,
                    "percent_change_60d": -8.15371304,
                    "percent_change_90d": -24.83779988,
                    "market_cap": 86858709944.73027,
                    "market_cap_dominance": 2.7305,
                    "fully_diluted_market_cap": 105681697392.48,
                    "tvl": None,
                    "last_updated": "2025-02-18T01:18:00.000Z",
                }
            },
        },
    },
}


cmc_top_10 = {
        "status": {
            "timestamp": "2025-02-18T00:13:11.844Z",
            "error_code": 0,
            "error_message": None,
            "elapsed": 171,
            "credit_count": 1,
            "notice": None,
        },
        "data": [
            {
                "id": 1,
                "rank": 1,
                "name": "Bitcoin",
                "symbol": "BTC",
                "slug": "bitcoin",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2010-07-13T00:05:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 1027,
                "rank": 2,
                "name": "Ethereum",
                "symbol": "ETH",
                "slug": "ethereum",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2015-08-07T14:45:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 52,
                "rank": 3,
                "name": "XRP",
                "symbol": "XRP",
                "slug": "xrp",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2013-08-04T18:50:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 825,
                "rank": 4,
                "name": "Tether USDt",
                "symbol": "USDT",
                "slug": "tether",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2015-02-25T13:30:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": {
                    "id": 1,
                    "name": "Ethereum",
                    "symbol": "ETH",
                    "slug": "ethereum",
                    "token_address": "0xdac17f958d2ee523a2206206994597c13d831ec7",
                },
            },
            {
                "id": 1839,
                "rank": 5,
                "name": "BNB",
                "symbol": "BNB",
                "slug": "bnb",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2017-07-25T04:30:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 5426,
                "rank": 6,
                "name": "Solana",
                "symbol": "SOL",
                "slug": "solana",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2020-04-10T04:55:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 3408,
                "rank": 7,
                "name": "USDC",
                "symbol": "USDC",
                "slug": "usd-coin",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2018-10-08T18:45:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": {
                    "id": 1,
                    "name": "Ethereum",
                    "symbol": "ETH",
                    "slug": "ethereum",
                    "token_address": "0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48",
                },
            },
            {
                "id": 74,
                "rank": 8,
                "name": "Dogecoin",
                "symbol": "DOGE",
                "slug": "dogecoin",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2013-12-15T14:40:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 2010,
                "rank": 9,
                "name": "Cardano",
                "symbol": "ADA",
                "slug": "cardano",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2017-10-01T20:30:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
            {
                "id": 1958,
                "rank": 10,
                "name": "TRON",
                "symbol": "TRX",
                "slug": "tron",
                "is_active": 1,
                "status": 1,
                "first_historical_data": "2017-09-13T01:15:00.000Z",
                "last_historical_data": "2025-02-18T00:00:00.000Z",
                "platform": None,
            },
        ],
    }
